# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty
#relative_permalinks: true

# http://jekyllrb.com/docs/github-pages/#project-page-url-structure
#baseurl: https://schoppach.github.io/
baseurl: /perso/ # for local testing

# Setup
title:            Remy's Blog
paginate:         1
author:
  name:           Remy Schoppach
  email:          remy.schoppach@gmail.com
